config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :spendings
  resources :buckets
  resources :categories
  resources :chapter_actions
  resources :relationships, only: [:create, :destroy]
  get 'chapters/index'

  devise_for :users, controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
 }
  root to: 'chapter_actions#index'

  get '/faq',                  to: 'static_pages#faq'
  get '/store',                to: 'static_pages#store'
  get '/control-panel',        to: 'static_pages#control_panel'
  get '/release-notes',        to: 'static_pages#release_notes'
  get '/chapters/',            to: 'chapters#index'
  get '/chapters/:slug',       to: 'chapters#show'
  get '/leaderboard',          to: 'chapters#leaderboard'
  get '/stats',                to: 'chapters#stats'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <section class="container">
    <a class="navbar-brand" href="/"><%= image_tag("SSDP20-logo-transparent.png", class: "img-fluid", style: "width: 70px;") %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to('Chapters', chapters_path, class: "nav-item nav-link") %>
        <%= link_to('Leaderboard', leaderboard_path, class: "nav-item nav-link") %>
        <%= link_to('Available Activities', categories_path, class: "nav-item nav-link") %>
        <%= link_to('How-to/FAQ', faq_path, class: "nav-item nav-link") %>
        <%= link_to('Store', store_path, class: "nav-item nav-link") %>
        <%= link_to('Stats', stats_path, class: "nav-item nav-link") %>

        <% if user_signed_in? %>
        <% if user_is_admin? %>
        <%= link_to('Control Panel', control_panel_path, class: "nav-item nav-link") %>
        <% else %>
        <%= link_to('Log Points', new_chapter_action_path, class: "nav-item nav-link") %>
        <% end %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-item nav-link") %>
        <% else %>
          <%= link_to('Login', new_user_session_path, class: "nav-item nav-link") %>
        <% end %>
      </div>
    </section>
  </div>
</nav>