config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :spendings
  resources :buckets
  resources :categories
  resources :chapter_actions
  resources :relationships, only: [:create, :destroy]
  get 'chapters/index'

  devise_for :users, controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
 }
  root to: 'chapter_actions#index'

  get '/faq',                  to: 'static_pages#faq'
  get '/store',                to: 'static_pages#store'
  get '/control-panel',        to: 'static_pages#control_panel'
  get '/release-notes',        to: 'static_pages#release_notes'
  get '/chapters/',            to: 'chapters#index'
  get '/chapters/:slug',       to: 'chapters#show'
  get '/leaderboard',          to: 'chapters#leaderboard'
  get '/stats',                to: 'chapters#stats'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  has_many :categories
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :set_bucket, only: [:show, :edit, :update, :destroy]

  # GET /buckets
  # GET /buckets.json
  def index
    @buckets = Bucket.all
  end

  # GET /buckets/1
  # GET /buckets/1.json
  def show
  end

  # GET /buckets/new
  def new
    @bucket = Bucket.new
  end

  # GET /buckets/1/edit
  def edit
  end

  # POST /buckets
  # POST /buckets.json
  def create
    @bucket = Bucket.new(bucket_params)

    respond_to do |format|
      if @bucket.save
        format.html { redirect_to @bucket, notice: 'Bucket was successfully created.' }
        format.json { render :show, status: :created, location: @bucket }
      else
        format.html { render :new }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buckets/1
  # PATCH/PUT /buckets/1.json
  def update
    respond_to do |format|
      if @bucket.update(bucket_params)
        format.html { redirect_to @bucket, notice: 'Bucket was successfully updated.' }
        format.json { render :show, status: :ok, location: @bucket }
      else
        format.html { render :edit }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buckets/1
  # DELETE /buckets/1.json
  def destroy
    @bucket.destroy
    respond_to do |format|
      format.html { redirect_to buckets_url, notice: 'Bucket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bucket
      @bucket = Bucket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bucket_params
      params.require(:bucket).permit(:name)
    end
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/views/buckets/_form.html.erb
<%= form_with(model: bucket, local: true) do |form| %>
  <% if bucket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bucket.errors.count, "error") %> prohibited this bucket from being saved:</h2>

      <ul>
      <% bucket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :bucket_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buckets/edit.html.erb
<h1>Editing Bucket</h1>

<%= render 'form', bucket: @bucket %>

<%= link_to 'Show', @bucket %> |
<%= link_to 'Back', buckets_path %>

app/views/buckets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buckets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buckets.each do |bucket| %>
      <tr>
        <td><%= bucket.name %></td>
        <td><%= link_to 'Show', bucket %></td>
        <td><%= link_to 'Edit', edit_bucket_path(bucket) %></td>
        <td><%= link_to 'Destroy', bucket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bucket', new_bucket_path %>

app/views/buckets/new.html.erb
<h1>New Bucket</h1>

<%= render 'form', bucket: @bucket %>

<%= link_to 'Back', buckets_path %>

app/views/buckets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bucket.name %>
</p>

<%= link_to 'Edit', edit_bucket_path(@bucket) %> |
<%= link_to 'Back', buckets_path %>