config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :spendings
  resources :buckets
  resources :categories
  resources :chapter_actions
  resources :relationships, only: [:create, :destroy]
  get 'chapters/index'

  devise_for :users, controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
 }
  root to: 'chapter_actions#index'

  get '/faq',                  to: 'static_pages#faq'
  get '/store',                to: 'static_pages#store'
  get '/control-panel',        to: 'static_pages#control_panel'
  get '/release-notes',        to: 'static_pages#release_notes'
  get '/chapters/',            to: 'chapters#index'
  get '/chapters/:slug',       to: 'chapters#show'
  get '/leaderboard',          to: 'chapters#leaderboard'
  get '/stats',                to: 'chapters#stats'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :chapter_actions
  belongs_to :bucket
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @chapter_building_categories = Category.where("bucket_id=1").order("default_points DESC")
    @policy_change_categories = Category.where("bucket_id=2").order("default_points DESC")
    @training_and_education_categories = Category.where("bucket_id=3").order("default_points DESC")
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @actions = ChapterAction.where("id = #{@category.id}")
  end

  # GET /categories/new
  def new
    @category = Category.new
    @buckets = Bucket.all.map{|c| [ c.name, c.id ] }
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @buckets = Bucket.all.map{|c| [ c.name, c.id ] }
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :desc, :default_points, :bucket_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc, id: :category_desc, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :default_points %>
    <%= form.number_field :default_points, id: :category_default_points, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :bucket_id %>
    <%= form.select(:bucket_id, options_for_select(@buckets), :prompt => "Select a bucket", :class => "form-control") %>
  </div>

  <div class="actions">
    <%= form.submit :class => "form-control" %>
  </div>
<% end %>

app/views/categories/_table.html.erb
<table class="activities-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Default points</th>
      <% if user_signed_in? && current_user.permissions == "administrator" %>
        <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.desc %></td>
        <td><%= category.default_points %></td>
        <% if user_signed_in? && current_user.permissions == "administrator" %>
            <td><%= link_to 'Show', category %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Available Activities</h1>
<p>These are all the available activities that your chapter can complete. <!--Not functional? <a href="#espanol">En Español</a>--></p>
<h2>Chapter Building</h2>
<%= render partial: "table", locals: {categories: @chapter_building_categories} %>
<h2>Policy Change</h2>
<%= render partial: "table", locals: {categories: @policy_change_categories} %>
<h2>Training and Education</h2>
<%= render partial: "table", locals: {categories: @training_and_education_categories} %>

<% if user_signed_in? %>
<% if current_user.permissions == "administrator" %>
<%= link_to 'New Category', new_category_path %>
<% end %>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @category.desc %>
</p>

<p>
  <strong>Default points:</strong>
  <%= @category.default_points %>
</p>

<p>
  <strong>Bucket:</strong>
  <%= Bucket.find(@category.bucket_id).name %>
</p>

<% if user_signed_in? %>
<% if user_is_admin? %>
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
<% end %>
<% end %>
<br>

<table width="100%">
  <tr>
    <th>Chapter</th>
    <th>Date</th>
  </tr>
<% @actions.each do |action| %>
  <tr>
    <td><%= User.where("id=#{action.user_id}")[0].name%></td>
    <td><%= action.created_at %></td>
  </tr>
<% end %>
</table>