config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :spendings
  resources :buckets
  resources :categories
  resources :chapter_actions
  resources :relationships, only: [:create, :destroy]
  get 'chapters/index'

  devise_for :users, controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
 }
  root to: 'chapter_actions#index'

  get '/faq',                  to: 'static_pages#faq'
  get '/store',                to: 'static_pages#store'
  get '/control-panel',        to: 'static_pages#control_panel'
  get '/release-notes',        to: 'static_pages#release_notes'
  get '/chapters/',            to: 'chapters#index'
  get '/chapters/:slug',       to: 'chapters#show'
  get '/leaderboard',          to: 'chapters#leaderboard'
  get '/stats',                to: 'chapters#stats'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  def send_report_email_daily
    if self.time_window == "daily"
      data = {}
      staffer = User.find(self.staffer_id)
      address = staffer.email
      following_ids = staffer.following_ids
      following_ids.each do |following_id|
        followed_account = User.find(following_id)
        actions =  ChapterAction.where("user_id = '#{followed_account.id}'").where(:date_completed => Date.yesterday..Date.today)
        action_data = []
        actions.each do |action|
          description = Category.find(action.category_id).name
          action_data << description
        end
        data[followed_account.name] = action_data
      end
      ReportMailer.report_email(data, address).deliver
    end
  end
    def send_report_email_weekly
    if self.time_window == "weekly"
      data = {}
      staffer = User.find(self.staffer_id)
      address = staffer.email
      following_ids = staffer.following_ids
      following_ids.each do |following_id|
        followed_account = User.find(following_id)
        actions =  ChapterAction.where("user_id = '#{followed_account.id}'").where(:date_completed => Date.today-6..Date.today)
        action_data = []
        actions.each do |action|
          description = Category.find(action.category_id).name
          action_data << description
        end
        data[followed_account.name] = action_data
      end
      ReportMailer.report_email(data, address).deliver
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:chapter_universe, :task_universe, :time_window)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :chapter_universe  %>
    <%= form.text_field :chapter_universe, id: :report_chapter_universe, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :task_universe %>
    <%= form.text_field :task_universe, id: :report_task_universe, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :time_window %>
    <%= form.text_field :time_window, id: :report_time_window, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit :class => "form-control" %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Chapter universe</th>
      <th>Task universe</th>
      <th>Time window</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.chapter_universe %></td>
        <td><%= report.task_universe %></td>
        <td><%= report.time_window %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Chapter universe:</strong>
  <%= @report.chapter_universe %>
</p>

<p>
  <strong>Task universe:</strong>
  <%= @report.task_universe %>
</p>

<p>
  <strong>Time window:</strong>
  <%= @report.time_window %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>